apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-demo
  labels:
    app: kubectl-demo
spec:
  selector:
    matchLabels:
      app: kube-demo
  template:
    metadata:
      labels:
        app: kube-demo
    spec:
      containers:
      - name: kube-demo
        image: root/kubedemo
        imagePullPolicy: Never
        ports:
        - containerPort: 8080


